# Generated by Django 5.1.4 on 2025-01-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_alter_testimonial_options_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
