# Generated by Django 5.1.4 on 2025-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='thumbnail_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
