# Generated by Django 5.1.4 on 2025-01-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_media_image_remove_skill_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar_binary',
            new_name='avatar',
        ),
    ]
