# Generated by Django 5.1.4 on 2025-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_avatar_binary_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_binary',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image_binary',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_binary',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='thumbnail_binary',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
