# Generated by Django 5.1.4 on 2025-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_blog_image_binary_remove_media_image_binary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
