# Generated by Django 5.1.4 on 2025-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog Profiles'},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials test'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, help_text='URL to blog image', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, help_text='URL to media image', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, help_text='External media link', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.URLField(blank=True, help_text='URL to portfolio image', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False, help_text='Mark if this is a key skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the skill name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=80, help_text='Skill proficiency score (out of 100)', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL to the testimonial thumbnail', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL to avatar image', max_length=500, null=True),
        ),
    ]
