# Generated by Django 5.1.4 on 2025-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_options_alter_contactprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=20, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog Profiles'},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
