# Generated by Django 5.1.4 on 2025-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_socialmedialink_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='url',
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='fb',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='ig',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='li',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='tw',
            field=models.TextField(default='-'),
        ),
    ]
