# Generated by Django 5.1.4 on 2025-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='ig',
            field=models.URLField(default='-'),
        ),
    ]
