# Generated by Django 5.1.4 on 2025-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_socialmedialink_ig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Employment'},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='about',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='ig',
            field=models.TextField(default='-'),
        ),
    ]
